### ISSUE TITLE
Install fails on MacOS 10.13.6

### ISSUE THREAD

**Issue by erikbohnsack** [src-d/lapjv#8] opened 2019-02-20 09:17 UTC
Hi! 

I get an error when trying to install when using pip. I'm using MacOS 10.13.6, using Conda's default environment. I have the following clang/g++ setup. 
``` 
g++ -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

Googling the errors points to std=c++11, but `"Darwin": ["-std=c++11", "-march=native", "-ftree-vectorize"]` works, as the command in the error log uses these flags. The closed issues related to installation on Mac didn't help. 

I'm using a default conda environment with python 3.7 and pip 19.0.1.

Here's the dump: 

```
pip install lapjv
Collecting lapjv
  Using cached https://files.pythonhosted.org/packages/98/75/d64ba8523db4168646a8f8d74f104c4eaea820ad0464a6b41ff1e692840f/lapjv-1.3.1.tar.gz
Requirement already satisfied: numpy in /anaconda3/envs/mot/lib/python3.7/site-packages (from lapjv) (1.15.4)
Building wheels for collected packages: lapjv
  Building wheel for lapjv (setup.py) ... error
  Complete output from command /anaconda3/envs/mot/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/q0/yv4nhd652f5_70s5r6tqhr3m0000gn/T/pip-install-avpiyzzw/lapjv/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /private/var/folders/q0/yv4nhd652f5_70s5r6tqhr3m0000gn/T/pip-wheel-_7qalaoh --python-tag cp37:
  running bdist_wheel
  running build
  running build_ext
  building 'lapjv' extension
  creating build
  creating build/temp.macosx-10.7-x86_64-3.7
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/anaconda3/envs/mot/include -arch x86_64 -I/anaconda3/envs/mot/include -arch x86_64 -I/anaconda3/envs/mot/lib/python3.7/site-packages/numpy/core/include -I/anaconda3/envs/mot/include/python3.7m -c python.cc -o build/temp.macosx-10.7-x86_64-3.7/python.o -std=c++11 -march=native -ftree-vectorize
  In file included from python.cc:6:
  ./lap.h:18:20: error: no template named 'tuple' in namespace 'std'
  always_inline std::tuple<cost, cost, idx, idx>
                ~~~~~^
  ./lap.h:41:15: error: no member named 'make_tuple' in namespace 'std'
    return std::make_tuple(umin, usubmin, j1, j2);
           ~~~~~^
  ./lap.h:52:20: error: no template named 'tuple' in namespace 'std'
  always_inline std::tuple<float, float, idx, idx>
                ~~~~~^
  ./lap.h:127:15: error: no member named 'make_tuple' in namespace 'std'
    return std::make_tuple(umin, usubmin, j1, j2);
           ~~~~~^
  ./lap.h:131:20: error: no template named 'tuple' in namespace 'std'
  always_inline std::tuple<double, double, idx, idx>
                ~~~~~^
  ./lap.h:206:15: error: no member named 'make_tuple' in namespace 'std'
    return std::make_tuple(umin, usubmin, j1, j2);
           ~~~~~^
  ./lap.h:228:20: error: no member named 'unique_ptr' in namespace 'std'
    auto free = std::unique_ptr<idx[]>(new idx[dim]);     // list of unassigned rows.
                ~~~~~^
  ./lap.h:228:31: error: 'idx' does not refer to a value
    auto free = std::unique_ptr<idx[]>(new idx[dim]);     // list of unassigned rows.
                                ^
  ./lap.h:224:20: note: declared here
  template <typename idx, typename cost>
                     ^
  ./lap.h:228:35: error: expected expression
    auto free = std::unique_ptr<idx[]>(new idx[dim]);     // list of unassigned rows.
                                    ^
  ./lap.h:229:23: error: no member named 'unique_ptr' in namespace 'std'
    auto collist = std::unique_ptr<idx[]>(new idx[dim]);  // list of columns to be scanned in various ways.
                   ~~~~~^
  ./lap.h:229:34: error: 'idx' does not refer to a value
    auto collist = std::unique_ptr<idx[]>(new idx[dim]);  // list of columns to be scanned in various ways.
                                   ^
  ./lap.h:224:20: note: declared here
  template <typename idx, typename cost>
                     ^
  ./lap.h:229:38: error: expected expression
    auto collist = std::unique_ptr<idx[]>(new idx[dim]);  // list of columns to be scanned in various ways.
                                       ^
  ./lap.h:230:23: error: no member named 'unique_ptr' in namespace 'std'
    auto matches = std::unique_ptr<idx[]>(new idx[dim]);  // counts how many times a row could be assigned.
                   ~~~~~^
  ./lap.h:230:34: error: 'idx' does not refer to a value
    auto matches = std::unique_ptr<idx[]>(new idx[dim]);  // counts how many times a row could be assigned.
                                   ^
  ./lap.h:224:20: note: declared here
  template <typename idx, typename cost>
                     ^
  ./lap.h:230:38: error: expected expression
    auto matches = std::unique_ptr<idx[]>(new idx[dim]);  // counts how many times a row could be assigned.
                                       ^
  ./lap.h:231:17: error: no member named 'unique_ptr' in namespace 'std'
    auto d = std::unique_ptr<cost[]>(new cost[dim]);      // 'cost-distance' in augmenting path calculation.
             ~~~~~^
  ./lap.h:231:28: error: 'cost' does not refer to a value
    auto d = std::unique_ptr<cost[]>(new cost[dim]);      // 'cost-distance' in augmenting path calculation.
                             ^
  ./lap.h:224:34: note: declared here
  template <typename idx, typename cost>
                                   ^
  ./lap.h:231:33: error: expected expression
    auto d = std::unique_ptr<cost[]>(new cost[dim]);      // 'cost-distance' in augmenting path calculation.
                                  ^
  ./lap.h:232:20: error: no member named 'unique_ptr' in namespace 'std'
    auto pred = std::unique_ptr<idx[]>(new idx[dim]);     // row-predecessor of column in augmenting/alternating path.
                ~~~~~^
  fatal error: too many errors emitted, stopping now [-ferror-limit=]
  20 errors generated.
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for lapjv
  Running setup.py clean for lapjv
Failed to build lapjv
Installing collected packages: lapjv
  Running setup.py install for lapjv ... error
    Complete output from command /anaconda3/envs/mot/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/q0/yv4nhd652f5_70s5r6tqhr3m0000gn/T/pip-install-avpiyzzw/lapjv/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/q0/yv4nhd652f5_70s5r6tqhr3m0000gn/T/pip-record-66ygc0ip/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'lapjv' extension
    creating build
    creating build/temp.macosx-10.7-x86_64-3.7
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/anaconda3/envs/mot/include -arch x86_64 -I/anaconda3/envs/mot/include -arch x86_64 -I/anaconda3/envs/mot/lib/python3.7/site-packages/numpy/core/include -I/anaconda3/envs/mot/include/python3.7m -c python.cc -o build/temp.macosx-10.7-x86_64-3.7/python.o -std=c++11 -march=native -ftree-vectorize
    In file included from python.cc:6:
    ./lap.h:18:20: error: no template named 'tuple' in namespace 'std'
    always_inline std::tuple<cost, cost, idx, idx>
                  ~~~~~^
    ./lap.h:41:15: error: no member named 'make_tuple' in namespace 'std'
      return std::make_tuple(umin, usubmin, j1, j2);
             ~~~~~^
    ./lap.h:52:20: error: no template named 'tuple' in namespace 'std'
    always_inline std::tuple<float, float, idx, idx>
                  ~~~~~^
    ./lap.h:127:15: error: no member named 'make_tuple' in namespace 'std'
      return std::make_tuple(umin, usubmin, j1, j2);
             ~~~~~^
    ./lap.h:131:20: error: no template named 'tuple' in namespace 'std'
    always_inline std::tuple<double, double, idx, idx>
                  ~~~~~^
    ./lap.h:206:15: error: no member named 'make_tuple' in namespace 'std'
      return std::make_tuple(umin, usubmin, j1, j2);
             ~~~~~^
    ./lap.h:228:20: error: no member named 'unique_ptr' in namespace 'std'
      auto free = std::unique_ptr<idx[]>(new idx[dim]);     // list of unassigned rows.
                  ~~~~~^
    ./lap.h:228:31: error: 'idx' does not refer to a value
      auto free = std::unique_ptr<idx[]>(new idx[dim]);     // list of unassigned rows.
                                  ^
    ./lap.h:224:20: note: declared here
    template <typename idx, typename cost>
                       ^
    ./lap.h:228:35: error: expected expression
      auto free = std::unique_ptr<idx[]>(new idx[dim]);     // list of unassigned rows.
                                      ^
    ./lap.h:229:23: error: no member named 'unique_ptr' in namespace 'std'
      auto collist = std::unique_ptr<idx[]>(new idx[dim]);  // list of columns to be scanned in various ways.
                     ~~~~~^
    ./lap.h:229:34: error: 'idx' does not refer to a value
      auto collist = std::unique_ptr<idx[]>(new idx[dim]);  // list of columns to be scanned in various ways.
                                     ^
    ./lap.h:224:20: note: declared here
    template <typename idx, typename cost>
                       ^
    ./lap.h:229:38: error: expected expression
      auto collist = std::unique_ptr<idx[]>(new idx[dim]);  // list of columns to be scanned in various ways.
                                         ^
    ./lap.h:230:23: error: no member named 'unique_ptr' in namespace 'std'
      auto matches = std::unique_ptr<idx[]>(new idx[dim]);  // counts how many times a row could be assigned.
                     ~~~~~^
    ./lap.h:230:34: error: 'idx' does not refer to a value
      auto matches = std::unique_ptr<idx[]>(new idx[dim]);  // counts how many times a row could be assigned.
                                     ^
    ./lap.h:224:20: note: declared here
    template <typename idx, typename cost>
                       ^
    ./lap.h:230:38: error: expected expression
      auto matches = std::unique_ptr<idx[]>(new idx[dim]);  // counts how many times a row could be assigned.
                                         ^
    ./lap.h:231:17: error: no member named 'unique_ptr' in namespace 'std'
      auto d = std::unique_ptr<cost[]>(new cost[dim]);      // 'cost-distance' in augmenting path calculation.
               ~~~~~^
    ./lap.h:231:28: error: 'cost' does not refer to a value
      auto d = std::unique_ptr<cost[]>(new cost[dim]);      // 'cost-distance' in augmenting path calculation.
                               ^
    ./lap.h:224:34: note: declared here
    template <typename idx, typename cost>
                                     ^
    ./lap.h:231:33: error: expected expression
      auto d = std::unique_ptr<cost[]>(new cost[dim]);      // 'cost-distance' in augmenting path calculation.
                                    ^
    ./lap.h:232:20: error: no member named 'unique_ptr' in namespace 'std'
      auto pred = std::unique_ptr<idx[]>(new idx[dim]);     // row-predecessor of column in augmenting/alternating path.
                  ~~~~~^
    fatal error: too many errors emitted, stopping now [-ferror-limit=]
    20 errors generated.
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/anaconda3/envs/mot/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/q0/yv4nhd652f5_70s5r6tqhr3m0000gn/T/pip-install-avpiyzzw/lapjv/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/q0/yv4nhd652f5_70s5r6tqhr3m0000gn/T/pip-record-66ygc0ip/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/q0/yv4nhd652f5_70s5r6tqhr3m0000gn/T/pip-install-avpiyzzw/lapjv/
```

I understand if this is shouldn't be on your table as I would guess that it has something to do with g++/clang,  but I figured I could post it here anyways. Any help is appreciated. 

Thanks!

**Comment by vmarkovtsev** [comment] 2019-02-20 10:52
Hi,

I have had several users who had problems with installing lapjv on macOS with Conda.

- Conda is officially not supported on any OS, nor it will ever be.
- The problem is with Conda environment specifically, which is screwed regarding the C++ compilation.

So I am closing this because (1) it has nothing to do with lapjv native code, and (2) it relates to an unsupported environment.

Note after closing: there should be similar issues here, people reported that some hacks did help.

❤️

**Closed by vmarkovtsev** 2019-02-20 10:52 UTC
